# superuser permission required
sudo: required
services:
  - docker

before_install:
  - docker build -t s29sharma/docker-react -f Dockerfile.dev .

script: 
  - docker run s29sharma/docker-react npm run test -- --coverage